### ISSUE TITLE
Curl dependent on nonexistant libwolfssl5.4

### ISSUE THREAD

**Issue by jeisom** [openwrt/packages#19019]
Maintainer: stangri@github-user (find it by checking history of the package Makefile)
Environment: [22.03.0-rc5 mvebu cortexa9 linksys_wrt1900ac-v1

Description:
I installed OpenWrt 22.03.0-rc5 on wrt1900ac-v1 and I can't install curl as it depends on libwolfssl5.4 and libwolfssl5.3 is the newest available.

**Comment by cmonty14** [comment]
Confirm issue with curl_7.83.1 on *mipsel_24kc*.

**Comment by BKPepe** [comment]
Reference: https://github.com/openwrt/openwrt/issues/10302

Fixed by https://github.com/openwrt/packages/pull/19008

**Comment by cmonty14** [comment]
> Reference: [openwrt/openwrt#10302](https://github.com/openwrt/openwrt/issues/10302)
> 
> Fixed by #19008

You closed this issue, but it's not solved, yet.
I understand there's a pull request, but as long as this pull request is not completed, the issue is not resolved.

**Comment by BKPepe** [comment]
The pull request was already merged when I wrote my comment and it was not reverted. You need to wait until buildbots will compile the packages for your device, and they will be available to install. It could take up to 24/48 hours.

**Comment by cmonty14** [comment]
> The pull request was already merged when I wrote my comment and it was not reverted. You need to wait until buildbots will compile the packages for your device, and they will be available to install. It could take up to 24/48 hours.

Thanks for confirmation.

**Comment by adamcstephens** [comment]
Will the #19008 change be applied to the 22.03 branch as well? rc5 is currently broken as is.

**Comment by karafen** [comment]
> Will the #19008 change be applied to the 22.03 branch as well? rc5 is currently broken as is.
A similar question, every day I wait for an update, but so far it has not been fixed!
Corrected only in snapshot.

**Comment by stangri** [comment]
> Will the #19008 change be applied to the 22.03 branch as well? rc5 is currently broken as is.

I cherry-picked @neheb's fix for 22.03 it should be available when buildbots get to it.
