### ISSUE TITLE
rust: Update to 1.90.0 build error

### ISSUE THREAD

**Issue by openips** [openwrt/packages#27485]
### Package Name

rust

### Maintainer

@1715173329 

### OpenWrt Version

SNAPSHOT

### OpenWrt Target/Subtarget

amd64

### Steps to Reproduce

build error 
```

error: failed to calculate checksum of: /LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src/vendor/serde-1.0.215/Cargo.toml.orig

Caused by:
  failed to open file `/LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src/vendor/serde-1.0.215/Cargo.toml.orig`

Caused by:
  No such file or directory (os error 2)
failed to run: /LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src/src/bootstrap/Cargo.toml -Zroot-dir=/LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src
Build completed unsuccessfully in 0:00:20
make[3]: *** [Makefile:108: /LEDE/openwrt-x64/build_dir/target-x86_64_musl/host/rustc-1.90.0-src/.built] Error 1
make[3]: Leaving directory '/LEDE/openwrt-x64/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#31.15#26.15#86.10
    ERROR: package/feeds/packages/rust [host] failed to build.
make[2]: *** [package/Makefile:181: package/feeds/packages/rust/host/compile] Error 1
make[2]: Leaving directory '/LEDE/openwrt-x64'
make[1]: *** [package/Makefile:177: /LEDE/openwrt-x64/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/LEDE/openwrt-x64'
make: *** [/LEDE/openwrt-x64/include/toplevel.mk:233: world] Error 2
```

### Actual Behaviour

build error 

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by zxlhhyccc** [comment]
Me too. This file was automatically deleted during the build.

**Comment by benma** [comment]
The Cargo.toml.orig files also started appearing for me in the vendor folder. `.orig` was in my `.gitignore`, which lead to this issue in CI, as the files were not committed. 

I couldn't find any info about these .orig files.

Edit: found the commit that introduced the change: https://github.com/rust-lang/cargo/commit/29ecb7f36a963bed4729bd6909200b4302a366a5

**Comment by openips** [comment]
fixed with pr https://github.com/openwrt/packages/pull/27487

**Comment by oyvindln** [comment]
Shouldn't this still be open? The the pr isn't merged yet and it's still happening for me at least

**Comment by grosjo** [comment]
Same error here

```
CARGO_HOME=/data/openwrt/wr650/dl/cargo TARGET_CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/data/openwrt/wr650/build_dir/target-mips_24kc_musl/rust-1.90.0=rust-1.90.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" python3 /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/x.py --build-dir /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/build dist build-manifest rustc rust-std cargo llvm-tools rust-src
Building bootstrap
error: failed to calculate checksum of: /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/vendor/serde-1.0.215/Cargo.toml.orig

Caused by:
  failed to open file `/data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/vendor/serde-1.0.215/Cargo.toml.orig`

Caused by:
  No such file or directory (os error 2)
failed to run: /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/src/bootstrap/Cargo.toml -Zroot-dir=/data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src
Build completed unsuccessfully in 0:00:00
make[3]: *** [Makefile:108: /data/openwrt/wr650/build_dir/target-mips_24kc_musl/host/rustc-1.90.0-src/.built] Error 1
make[3]: Leaving directory '/data/openwrt/wr650/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#0.48#0.17#0.65
    ERROR: package/feeds/packages/rust [host] failed to build.
make[2]: *** [package/Makefile:181: package/feeds/packages/rust/host/compile] Error 1
make[2]: Leaving directory '/data/openwrt/wr650'
make[1]: *** [package/Makefile:177: /data/openwrt/wr650/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/data/openwrt/wr650'
make: *** [/data/openwrt/wr650/include/toplevel.mk:233: world] Error 2

```
