### ISSUE TITLE
mc: Buildbot is failing due to missing librpc dependency

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#7180]
@dibdot 

https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/mc/compile.txt

**Comment by jow-** [comment]
@dibdot  @neheb - try `CONFIGURE_VARS += ac_cv_func_pmap_set=no`

**Comment by dibdot** [comment]
@jow- many thanks, I'll try that.

**Comment by dibdot** [comment]
@jow- I've added this variable to my Makefile but mc generation dies here locally as long as I build librpc in parallel.

**Comment by tripolar** [comment]
librpc should get dropped/removed. See https://github.com/openwrt/openwrt/pull/1280

**Comment by diizzyy** [comment]
Close this issue as it's fixed

**Comment by dibdot** [comment]
@diizzyy I would like to keep this open as long as the underlying librpc issue hasn't be fixed.

**Comment by lyssdod** [comment]
Hi @neheb and @dibdot, are there any news regarding this? The buildlog you've provided is 404 now

**Comment by neheb** [comment]
This has been fixed AFAIK

**Comment by dibdot** [comment]
Well, not really fixed - I've just disabled VFS support by default (again). Anyway, let's close this one for now.

**Comment by lyssdod** [comment]
@dibdot but what needs to be done to fix it properly? Fix build with libtrpc?
