### ISSUE TITLE
tor fails to compile since seccomp was added (buildbot)

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#935]
```
checking for seccomp.h... yes
checking for library containing seccomp_init... -lseccomp
...later...
src/common/sandbox.c: In function 'sb_mmap2':
src/common/sandbox.c:345:58: error: 'MAP_STACK' undeclared (first use in this function)
        SCMP_CMP(3, SCMP_CMP_EQ,MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK));
```
reported by:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/tor/compile.txt

This is some cross compile / build system issue / possibly target issue
"-lseccomp" detection works but that flag is not used in compilation process later.

Unclear for me if tor on MIPS needs some sandbox.c changes like arm does
( https://gitweb.torproject.org/tor.git/commit/src/common/sandbox.c?id=b0c1c700114aa8d4dfc180d85870c5bbe15fcacb )

**Comment by champtar** [comment]
@nmav, maybe libseccomp should depend on KERNEL_SECCOMP?

**Comment by nmav** [comment]
Done

**Comment by dangowrt** [comment]
This still doesn't account for tor depending on libseccomp if configure finds it.... So tor build still breaks because of that missing dependency now. I reckon this could be fixed in tor/Makefile by depending on +KERNEL_SECCOMP:libseccomp.
